### PR TITLE
Do not fail OCI upload when no subjects

### LINKED ISSUE #402: Unable to use artifacts.taskrun.storage: oci for all TaskRuns
# Expected Behavior
`artifacts.taskrun.storage: oci` can be used for all TaskRuns, including ones that do not produce an image.

# Actual Behavior
When using a Task that does not produce an image, e.g. [git-clone](https://github.com/tektoncd/catalog/blob/main/task/git-clone/0.5/git-clone.yaml), the Tekton Chains controller fails with the following error:
```
2022-03-24T16:12:02.318Z info Storing payload on TaskRun lui/git-clone-run-4qckv
2022-03-24T16:12:02.318Z error Did not find anything to attest
2022-03-24T16:12:02.642Z info Uploaded entry to https://rekor.sigstore.dev with index 1784594
2022-03-24T16:12:02.683Z error Returned an error
2022-03-24T16:12:02.683Z info Event(v1.ObjectReference{Kind:"TaskRun", Namespace:"lui", Name:"git-clone-run-4qckv", UID:"bc2abbed-90c5-4a2e-aa4f-94e99e5ea76c", APIVersion:"tekton.dev/v1beta1", ResourceVersion:"13813547", FieldPath:""}): type: 'Warning' reason: 'InternalError' 1 error occurred:
	* Did not find anything to attest

```

The error above happens 7 times.

# Steps to Reproduce the Problem

1. Set `artifacts.taskrun.storage: oci` in the `chains-config` ConfigMap.
2. Start a task that does not produce an container image.
3. Inspect Tekton Chains controller logs for errors.

Note that because I also have `transparency.enabled: "true"` in the `chains-config` ConfigMap, each retry generates a new entry in the transparency log:
```
2022-03-24T16:11:55.758Z info Uploaded entry to https://rekor.sigstore.dev with index 1784588
2022-03-24T16:11:56.276Z info Uploaded entry to https://rekor.sigstore.dev with index 1784589
2022-03-24T16:11:57.032Z info Uploaded entry to https://rekor.sigstore.dev with index 1784590
2022-03-24T16:11:58.405Z info Uploaded entry to https://rekor.sigstore.dev with index 1784591
2022-03-24T16:11:59.832Z info Uploaded entry to https://rekor.sigstore.dev with index 1784592
2022-03-24T16:12:01.066Z info Uploaded entry to https://rekor.sigstore.dev with index 1784593
2022-03-24T16:12:02.642Z info Uploaded entry to https://rekor.sigstore.dev with index 1784594
```

# Additional Info

- Kubernetes version:

```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"archive", BuildDate:"2021-07-22T00:00:00Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+b93fd35", GitCommit:"3a0f2c90b43e6cffd07f57b5b78dd9f083e47ee2", GitTreeState:"clean", BuildDate:"2022-02-11T05:26:59Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```

- OpenShift version:

```
Client Version: 4.8.0-202201210133.p0.g88e7eba.assembly.stream-88e7eba
Server Version: 4.9.23
Kubernetes Version: v1.22.3+b93fd35
```
- Tekton Pipeline version:

```
Client version: 0.21.0
Pipeline version: v0.28.3
Triggers version: v0.16.1
```

Obviously, a TaskRun that does not produce an image makes it difficult for Tekton Chains to determine which repository the attestation should be stored in. Maybe `storage.oci.repository` is the answer to that. (I have not been successful in getting `storage.oci.repository` to work at all - it's always completely ignored by the Tekton Chains controller.)

### PR DESCRIPTION
**Pull request by lcarva**
Instead, log an INFO message and carry on. Many tasks in a given Tekton
Pipeline may not produce an image. For example, a Pipeline may contain
tasks to clone a git repository and run different kinds of tests.

Triggering an error means the TaskRun resource is re-added to the
operator reconcilliation loop, causing the same resource to be
re-processed multiple times. If other storage backends are also
configured, payloads are regenerated and re-uploaded to those backends.
This multiple upload behavior is also seen when rekor integration is
enabled.

Fixes #402

Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

### CODE REVIEW

File: pkg/chains/storage/oci/oci.go [hunk 1]
```diff
@@ -90,9 +90,13 @@ func (b *Backend) StorePayload(ctx context.Context, rawPayload []byte, signature
 		}
 
 		// This can happen if the Task/TaskRun does not adhere to specific naming conventions
-		// like *IMAGE_URL that would serve as hints.
+		// like *IMAGE_URL that would serve as hints. This may be intentional for a Task/TaskRun
+		// that is not intenteded to produce an image, e.g. git-clone.
```
Comment (simonbaird) [inline pkg/chains/storage/oci/oci.go:94]: "intended"

File: pkg/chains/storage/oci/oci_test.go [hunk 2]
```diff
@@ -63,7 +63,7 @@ func TestBackend_StorePayload(t *testing.T) {
 					PayloadFormat: "in-toto",
 				},
 			},
-			wantErr: true,
+			wantErr: false,
```
Comment (simonbaird) [inline pkg/chains/storage/oci/oci_test.go:66]: Maybe you could add a new assertion here to cover the new behavior. I'm not sure what, but maybe that assert that the log entry was seen, or the function returned nil like it should have.

**Review by simonbaird — COMMENTED** [review]
Looks okay to me.

File: pkg/chains/storage/oci/oci.go (hunk 1 above)
Comment (lcarva) [reply pkg/chains/storage/oci/oci.go]: Thanks! Fixed.

File: pkg/chains/storage/oci/oci_test.go (hunk 2 above)
Comment (lcarva) [reply pkg/chains/storage/oci/oci_test.go:66]: By setting `wantErr` to `false`, the assertion on line 78 will check that the return value is `nil`. I'm not sure if looking back in the logs is needed. I don't see this currently being done in the code base.

Comment (simonbaird) [reply pkg/chains/storage/oci/oci_test.go:66]: Ack, sounds good.

**Comment by lcarva** [comment]
/assign @font

^ I _think_ I'm supposed to do that now based on the instructions.

@font, @priyawadhwa, I see you are marked as reviewers. Please, let me know what's the best way to have this changed reviewed.

**Review by priyawadhwa — APPROVED** [review]
Thanks for fixing this @lcarva ! I just kicked off the tests, once they're all green this should be good to merge 😄
